# NOTE: update this with your service name
service: TumpieAPI

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Name of the SST app that's deploying our infrastructure
  sstApp: ${self:custom.stage}-bumpieInfra

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    dataTableName: !ImportValue "${self:custom.sstApp}-tumpieDataInfra-TableName"
    notificationTableName: !ImportValue "${self:custom.sstApp}-tumpieNotificationInfra-TableName"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - !ImportValue "${self:custom.sstApp}-tumpieDataInfra-TableArn"
        - !ImportValue "${self:custom.sstApp}-tumpieNotificationInfra-TableArn"

functions:
  getData:
    handler: getData.main
    events:
      - http:
          path: data
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: updateData.main
    events:
      - http:
          path: data
          method: put
          cors: true
          authorizer: aws_iam

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # Cognito Identity Pool Policy
  - ${file(resources/cognito-policy.yml)}
